global:
  scrape_interval: 15s # 메트릭을 가져오는 주기

scrape_configs:
  - job_name: 'basicarch'
    metrics_path: '/actuator/prometheus' # 메트릭을 가져오는 경로
    static_configs:
      - targets: ['host.docker.internal:8085'] #메트릭을 가져올 주소
